name : dockerbuild

on : [push]

jobs :
  build :
    runs-on : ubuntu-latest
  
    steps : 
    - uses : actions/checkout@v2
    - name : dockerbuild
      run : |
        docker build -t myimage:1.0 .

